"""Render artifact/real_traffic.json into ../realtraffic.tex (included by main.tex)."""
import json, pathlib

HERE = pathlib.Path(__file__).parent
d = json.loads((HERE / "real_traffic.json").read_text())
P = d["policies"]
LABEL = {"ai_crawler": "AI crawler (declared)", "scanner": "Scanner (declared)",
         "seo_search_bot": "Search/SEO bot", "browser_like": "Browser-like UA",
         "http_library": "HTTP library / CLI", "other_bot": "Other bot", "mcp_client": "MCP client",
         "empty": "Empty UA", "other": "Other"}
PATHS = {"mcp_endpoint": r"\code{/mcp}", "root": r"\code{/}", "well_known": r"\code{/.well-known/*}",
         "crawler_meta": "robots/favicon/sitemap", "other_probe": "other paths (probes)", "health": r"\code{/healthz}"}


def pct(a, b):
    return f"{100 * a / b:.1f}\\%" if b else "--"


m = {
    "RTHours": d["window"]["hours"], "RTStart": d["window"]["start"][:10], "RTEnd": d["window"]["end"][:10],
    "RTRequests": f"\\num{{{d['requests']}}}", "RTSources": f"\\num{{{d['sources']}}}",
    "RTvSix": d["ipv6_sources"], "RTTopTen": f"{100 * d['top10_source_share']:.0f}\\%",
    "RTNonClient": f"\\num{{{P['v2']['non_mcp_client_requests']}}}",
    "RTvOneBlocked": f"\\num{{{P['v1']['blocked_at_gate']}}}", "RTvTwoBlocked": f"\\num{{{P['v2']['blocked_at_gate']}}}",
    "RTNoneAuth": f"\\num{{{P['none']['reached_auth']}}}", "RTvOneAuth": f"\\num{{{P['v1']['reached_auth']}}}",
    "RTvTwoAuth": f"\\num{{{P['v2']['reached_auth']}}}",
    "RTvOneUnwantedPct": pct(P["v1"]["non_mcp_client_blocked_at_gate"], P["v1"]["non_mcp_client_requests"]),
    "RTvTwoUnwantedPct": pct(P["v2"]["non_mcp_client_blocked_at_gate"], P["v2"]["non_mcp_client_requests"]),
}
out = ["% AUTO-GENERATED by artifact/gen_realtraffic_tex.py from real_traffic.json -- do not edit"]
out += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()]

rows = []
for k, n in d["ua_class_requests"].items():
    rows.append(f"{LABEL.get(k, k)} & \\num{{{n}}} & {pct(n, d['requests'])} & \\num{{{d['ua_class_sources'].get(k, 0)}}} \\\\")
prow = [f"{PATHS.get(k, k)} & \\num{{{n}}} & {pct(n, d['requests'])} & \\\\" for k, n in d["path_class"].items()]
out += [r"\newcommand{\RTCompositionTable}{%",
        r"\begin{table}[t]\centering\small",
        r"\caption{Real traffic to the public endpoint (\RTStart{} to \RTEnd{}, \RTHours\,h), operator traffic excluded. Classes are by user-agent.}",
        r"\label{tab:realcomp}",
        r"\begin{tabularx}{\columnwidth}{@{}Xrrr@{}}\toprule",
        r"Client class & Requests & Share & Sources \\ \midrule", *rows,
        r"\midrule \textit{Target} & & & \\", *prow,
        r"\bottomrule\end{tabularx}\end{table}}"]

prow2 = []
for tag, name in (("none", "No gate (auth only)"), ("v1", "Guardian v1"), ("v2", "Guardian v2")):
    p = P[tag]
    prow2.append(f"{name} & \\num{{{p['blocked_at_gate']}}} & \\num{{{p['reached_auth']}}} & "
                 f"{pct(p['non_mcp_client_blocked_at_gate'], p['non_mcp_client_requests'])} \\\\")
out += [r"\newcommand{\RTPolicyTable}{%",
        r"\begin{table}[t]\centering\small",
        r"\caption{The same real trace replayed through each policy on its own clock (replay reproduces the live server's status for 1211/1211 validation requests).}",
        r"\label{tab:realpolicy}",
        r"\begin{tabularx}{\columnwidth}{@{}Xrrr@{}}\toprule",
        r"Policy & \makecell[r]{Blocked\\at gate} & \makecell[r]{Reached\\auth} & \makecell[r]{Non-client\\blocked} \\ \midrule", *prow2,
        r"\bottomrule\end{tabularx}\end{table}}"]
(HERE.parent / "realtraffic.tex").write_text("\n".join(out) + "\n")
print("wrote", HERE.parent / "realtraffic.tex")
